#!/bin/bash
# decrypts all files in the specified directory 'dirname'
# into corresponding original files in local directory 'orgdirname' 
# expects also a keyfile argument, e.g. key.bin (to be kept secure)
# note that 'keygen' can generate a suitable keyfile of any given length 

PROGN=${0##*/}

case $# in
	0|1)
		printf "$PROGN quitting, requires keyfile and dirname arguments\n"
		exit 2;; 
	2)
      if ! [ -f "$1" ]; then
		printf "$PROGN quitting, keyfile $1 not found\n"
		printf "note that 'keygen' can generate a keyfile of any length\n"
		exit 2; fi
		if ! [ -d "$2" ]; then
		printf "$PROGN quitting, dirname $2 not found\n"
		exit 2; fi;;
	*) 
		printf "$PROGN quitting, too many arguments, needs keyfile and directory\n" 
		exit 2;;
esac
# output directory
OD=${2##*/}_org 
if ! [ -d "$OD" ]; then mkdir $OD; fi
for FILE in $2/*; do
    [ -f "$FILE" ] || continue
    let COUNT+=1
    symcrypt $1 $FILE | lzma -d -c > $OD/${FILE##*/}
done
printf "$PROGN decrypted $COUNT files into ./$OD/\n"
