#!/bin/bash
# general encryption-decryption test
# ecrypt encrypts all files in the given directory
# dcrypt decrypts back all the encrypted files

PROGN=${0##*/}

case $# in
	0)
		printf "$PROGN quitting, requires a directory argument\n"
		exit 2;; 
	1)
  		if ! [ -d "$1" ]; then
		printf "$PROGN quitting, dirname $1 not found\n"
		exit 2; fi;;
	*) 
		printf "$PROGN quitting, too many arguments, needs just a directory\n" 
		exit 2;;
esac

binkeygen 2048 > testkey.bin
printf "$PROGN generated testkey.bin\n"

ecrypt testkey.bin $1
dcrypt testkey.bin ./${1##*/}_ecr

printf "$PROGN found these differences:\n"
for FILE in $1/*; do
    [ -f "$FILE" ] || continue
    let COUNT+=1
 	diff $FILE ./${1##*/}_ecr_org/${FILE##*/} 
done
printf "$PROGN tested $COUNT files\n"
