#!/bin/bash
# encrypts all files in the specified directory 'dirname'
# into corresponding encrypted binary files in local directory 'dirname-ecr' 
# expects also a keyfile argument, e.g. key.bin (to be kept secure)
# note that 'keygen' can generate a suitable keyfile of any given length 

PROGN=${0##*/}

case $# in
	0|1)
		printf "$PROGN quitting, requires keyfile and dirname arguments\n"
		exit 2;; 
	2)
      if ! [ -f "$1" ]; then
		printf "$PROGN quitting, keyfile $1 not found\n"
		printf "note that 'keygen' can generate a keyfile of the right length\n"
		exit 2; fi
		if ! [ -d "$2" ]; then
		printf "$PROGN quitting, dirname $2 not found\n"
		exit 2; fi;;
	*) 
		printf "$PROGN quitting, too many arguments, needs keyfile and directory\n" 
		exit 2;;
esac
# output directory for encrypted versions
OD=${2##*/}_ecr
if ! [ -d "$OD" ]; then mkdir $OD; fi

for FILE in $2/*; do
    [ -f "$FILE" ] || continue
    let COUNT+=1
    lzma -z -c $FILE | symcrypt $1 > $OD/${FILE##*/}
done
printf "$PROGN encrypted $COUNT files into ./$OD/\n"
