#!/bin/bash
# generates random hex data '0-9a-f' of length given by the single argument
# when the requested size was odd, the output will be one byte longer
# as the .hex files should be always of an even length

if [ $# -ne 1 ]; then
	printf "$0: needs file size argument, e.g. obtained by 'stat -c%s myfile'\n" 1>&2 
	exit 2
fi
if [[ $(( $1 % 2 )) -eq 1 ]]; then SZ=$(( $1+1 )); else SZ=$1; fi
tr -dc '0-9a-f' < /dev/urandom | head -c $SZ > /dev/stdout
