#!/bin/bash
# hexadecimal encryption-decryption test
# hexecrypt encrypts all *.hex files in the current directory
# hexdcrypt decrypts back all *.scr binary encrypted files in the current directory

PROGN=${0##*/}

# find the first .hex file in this directory
HEXFILE=$( ls -1 *.hex 2>/dev/null | head -n 1 )
if [ -z "$HEXFILE" ]; then
	printf "$PROGN quitting, no .hex file here in $(pwd)\n" 
	exit 2
fi
# create the tests subdirectory if it does not exist and save the originals in it
[ -d tests ] || mkdir tests 
cp *.hex tests
printf "$PROGN saved the original *.hex files in 'tests' directory\n"

# generate keyfile key.bin, using the length of the first .hex file as a guide
KEYFILE='key.bin'
keygen $HEXFILE > $KEYFILE
printf "$PROGN generated keyfile '$KEYFILE' of %d bytes, use it for decrypting\n" $( stat -c%s $KEYFILE )

hexecrypt $KEYFILE
hexdcrypt $KEYFILE

printf "$PROGN found these differences:\n"
for F in *.hex; do
    [ -f "$F" ] || continue
    let COUNT+=1
 	diff $F tests/$F
	rm ${FILE%.hex}.scr
done
printf "$PROGN tested $COUNT files\n"
