#!/bin/bash
# hexadecimal encryption-decryption test
# hexecrypt encrypts all *.hex files in the current directory
# hexdcrypt decrypts back all *.scr binary encrypted files in the current directory

# find the first .hex file in this directory
HEXFILE=$( ls -1 *.hex 2>/dev/null | head -n 1 )
if [ -z "$HEXFILE" ]; then
	printf "${0##*/} quitting, no .hex file here in $(pwd)\n" 
	exit 2
fi
# create the tests subdirectory if it does not exist and save the originals in it
[ -d tests ] || mkdir tests 
cp *.hex tests
printf "${0##*/} saved the original *.hex files in 'tests' directory\n"

# generate keyfile key.bin, using the length of the first .hex file as a guide
KEYFILE='key.bin'
keygen $HEXFILE > $KEYFILE
printf "${0##*/} generated keyfile '$KEYFILE' of %d bytes, use it for decrypting\n" $( stat -c%s $KEYFILE )

hexecrypt $KEYFILE
hexdcrypt $KEYFILE

printf "${0##*/} found these differences:\n"
for F in *.hex; do
    [ -f "$F" ] || continue
    let COUNT+=1
 	diff $F tests/$F 
done
printf "${0##*/} tested $COUNT files\n"
