#!/bin/bash
# invoke as: sudo ./install
# installs TokenCrypt utilities in /usr/local/bin

PROGS='symcrypt keygen ncrpt expcrypt impcrypt crptest expimptest'
chmod 755 $PROGS
sudo cp $PROGS /usr/local/bin
printf "Installed TokenCrypt utilities in /usr/local/bin\n"
