#!/bin/bash
# invoke as: sudo ./install
# installs TokenCrypt utilities in /usr/local/bin

cargo install --path crypt --root . symcrypt
cargo install --path hex2bin --root . hexcheck
cargo install --path bin2hex --root . hexify

strip bin/*
chmod 755 bin/*
mv bin/* .

PROGS='symcrypt hexcheck hexify keygen ncrpt expcrypt impcrypt crptest expimptest'
chmod 755 $PROGS
sudo cp $PROGS /usr/local/bin
printf "Installed TokenCrypt utilities in /usr/local/bin\n"
