#!/bin/bash
# given a filename argument, writes to stdout a random encryption key
# for it of the same length (as the named file).

PROGN=${0##*/}

case $# in
	0)
		printf 1>&2 "$PROGN quitting, requires a file argument\n"
		exit 2;; 
	1)
  		if ! [ -f "$1" ]; then
		printf 1>&2 "$PROGN quitting, file $1 not found\n"
		exit 2; fi;;
	*) 
		printf 1>&2 "$PROGN quitting: too many arguments, needs one file\n" 
		exit 2;;
esac

head -c `stat -c%s $1` /dev/urandom
