#!/bin/bash
# given some typical file as an argument, generates an appropriate key for it
# recognises hexadecimal by extension .hex 

PROGN=${0##*/}

case $# in
	0)
		printf 1>&2 "$PROGN quitting, requires a file argument\n"
		exit 2;; 
	1)
  		if ! [ -f "$1" ]; then
		printf 1>&2 "$PROGN quitting, file $1 not found\n"
		exit 2; fi;;
	*) 
		printf 1>&2 "$PROGN quitting: too many arguments, needs one file\n" 
		exit 2;;
esac

LASTEXT=${1##*.}

if [ "$LASTEXT" == 'hex' ]; then 
	SIZE=$(( $( stat -c%s $1 )/2 + 1 ))
else SIZE=$( stat -c%s $1 )
fi
head -c $SIZE /dev/urandom