#!/bin/bash
# decrypts all files in the specified directory 'dirname'
# using corresponding keys in the specified directory 'keysname'
# into corresponding original files in local directory 'orgdirname' 

PNAME=${0##*/}

case $# in
	0|1|2)
		printf "$PNAME quitting, requires keysdir and encrypteddir arguments\n"
		exit 2;; 
	3)
      if ! [ -d "$1" ]; then
		printf "$PNAME quitting, keys directory $1 not found\n"
		exit 2; fi
		if ! [ -d "$2" ]; then
		printf "$PNAME quitting, encrypted directory $2 not found\n"
		exit 2; fi;;
		if ! [ -d "$3" ]; then
		printf "$PNAME quitting, compressed encrypted files directory $3 not found\n"
		exit 2; fi;;
	*) 
		printf "$PNAME quitting, needs keysydir encrypteddir compressedencrypteddir\n" 
		exit 2;;
esac

# output directory
OD=${2##*/}-org 
if ! [ -d "$OD" ]; then mkdir $OD; fi

for FILE in $1/*; do
    [ -f "$FILE" ] || continue
    let COUNT+=1
	FILEND=${FILE##*/}
	if [ -f $2/$FILEND ]; then
		symcrypt $1/$FILE $2/$FILE > $OD/$FILEND
	else if [ -f $3/$FILEND ]; then
		symcrypt $1/$FILE $3/$FILE | lzma -d -c > $OD/$FILEND
	else 
		printf "$PNAME quitting, failed to find file $FILEND\n" 
		exit 2;;
	fi; fi
done
printf "$PNAME decrypted $count files into ./$OD/\n"
