#!/bin/bash
# decrypts all files in the specified directory 'dirname'
# using corresponding keys in the specified directory 'keysname'
# into corresponding original files in local directory 'orgdirname' 

PNAME=${0##*/}

case $# in
	0|1|2)
		printf "$PNAME quitting, needs keysdir encrypteddir compressedencrypteddir\n" 
		exit 2;; 
	3)
      if ! [ -d "$1" ]; then
		printf "$PNAME quitting, keys directory $1 not found\n"
		exit 2; fi
		if ! [ -d "$2" ]; then
		printf "$PNAME quitting, encrypted directory $2 not found\n"
		exit 2; fi
		if ! [ -d "$3" ]; then
		printf "$PNAME quitting, compressed encrypted directory $3 not found\n"
		exit 2; fi;;
	*) 
		printf "$PNAME quitting, needs keysdir encrypteddir compressedencrypteddir\n" 
		exit 2;;
esac

# make output directory _org
OD=${2##*/}_org 
if ! [ -d "$OD" ]; then mkdir $OD; fi

# loop through the keys
for FILE in $1/*; do
    [ -f "$FILE" ] || continue
    let COUNT+=1
	FILEND=${FILE##*/}
	if [ -f $2/$FILEND ]; then
		symcrypt $FILE $2/$FILEND > $OD/$FILEND
	else if [ -f $3/$FILEND ]; then
		symcrypt $FILE $3/$FILEND | lzma -d -c > $OD/$FILEND
	else 
		printf "$PNAME quitting, failed to find encrypted file $FILEND\n" 
		exit 2;;
	fi; fi
done
printf "$PNAME decrypted $COUNT files into ./$OD/\n"
