#!/bin/bash
# general encryption-decryption test
# ecrypt encrypts all files in the given directory
# dcrypt decrypts back all the encrypted files

PROGN=${0##*/}

case $# in
	0)
		printf "$PROGN quitting, requires a path argument\n"
		exit 2;; 
	1)
  		if ! [ -d "$1" ]; then
		printf "$PROGN quitting, input directory name $1 not found\n"
		exit 2; fi;;
	*) 
		printf "$PROGN quitting, too many arguments, needs just one input path\n" 
		exit 2;;
esac

DIREND=${1##*/}
# output directories preparation
if [ -d "$DIREND"_ecr ]; then rm -r "$DIREND"_ecr/*
else mkdir "$DIREND"_ecr; fi
if [ -d "$DIREND"_elz ]; then rm -r "$DIREND"_elz/*
else mkdir "$DIREND"_elz; fi
if [ -d "$DIREND"_key ]; then rm -r "$DIREND"_key/*
else mkdir "$DIREND"_key; fi

superecrypt $1
superdcrypt "$DIREND"_key "$DIREND"_ecr "$DIREND"_elz

printf "$PROGN found these differences:\n"
for FILE in $1/*; do
    [ -f "$FILE" ] || continue
    let COUNT+=1
 	diff $FILE "$DIREND"_ecr_org/${FILE##*/} 
done
rm -rf "$DIREND"_ecr "$DIREND"_ecr_org "$DIREND"_elz "$DIREND"_key
printf "$PROGN tested $COUNT files\n"
