#!/bin/bash
# invoke as: ./uninstall
# uninstalls TokenCrypt utilities from /usr/local/bin
PROGS='bin/xorfork bin/symcrypt bin/hexcheck bin/hexify keygen ncrpt dcrpt pack unpack crptest packtest'
for PROG in $PROGS; do
    sudo rm /usr/local/bin/$PROG
done
printf "Uninstalled TokenCrypt utilities from /usr/local/bin\n"
