#!/bin/bash
# invoke as: sudo ./uninstall
# uninstalls TokenCrypt utilities from /usr/local/bin
PROGS='symcrypt hexcheck keygen ncrpt dcrpt crptest'
rm $PROGS /usr/local/bin
printf "Uninstalled TokenCrypt utilities from /usr/local/bin\n"
